Repository Factorio-Biter-Battles/Factorio-Biter-Battles, pull requests merged in 2023-10, with the labels that each got.

#354 Special game disable sciences from sending
  comfy_panel/special_games.lua
  maps/biter_battles_v2/gui.lua
  maps/biter_battles_v2/init.lua
Labels: live-testing

#352 Introduce map reroll
  .gitignore
  comfy_panel/config.lua
  maps/biter_battles_v2/difficulty_vote.lua
  maps/biter_battles_v2/game_over.lua
  maps/biter_battles_v2/gui.lua
  maps/biter_battles_v2/init.lua
  utils/token.lua
Labels: live-testing

#353 Special game Mixed ore map
  comfy_panel/special_games.lua
  maps/biter_battles_v2/game_over.lua
  maps/biter_battles_v2/init.lua
  maps/biter_battles_v2/mixed_ore_map.lua
  maps/biter_battles_v2/terrain.lua
  utils/get_noise.lua
Labels: enhancement, live-testing, live-testing-captain, ready-for-merge

#363 Add info.json file
  info.json
Labels: documentation, live-testing, live-testing-captain, ready-for-merge

#382 Reveal map at start
  comfy_panel/config.lua
  maps/biter_battles_v2/game_over.lua
  maps/biter_battles_v2/init.lua
  maps/biter_battles_v2/main.lua
Labels: enhancement, live-testing, live-testing-captain, ready-for-merge

#389 perf : Biter terrain tiles optimization
  maps/biter_battles_v2/biter_texture.lua
  maps/biter_battles_v2/terrain.lua
Labels: live-testing, live-testing-captain, perf, ready-for-merge

#394 perf : Increase refresh threat min delay and optim on code
  maps/biter_battles_v2/gui.lua
Labels: live-testing, live-testing-captain, perf, ready-for-merge

#400 perf : optim damage event and increased refresh delay for healthbar of bosses
  functions/boss_unit.lua
Labels: live-testing, live-testing-captain, perf, ready-for-merge
