Repository Factorio-Biter-Battles/Factorio-Biter-Battles, pull requests merged in 2023-11, with the labels that each got.

#395 Remove more unused modules
  functions/connect_belts.lua
  functions/create_entity_chain.lua
  functions/create_tile_chain.lua
  functions/maze.lua
  functions/noise_vector_path.lua
  functions/room_generator.lua
  functions/tick_tack_trap.lua
  functions/unearthing_biters.lua
  functions/unearthing_worm.lua
  tools/cheat_mode.lua
  tools/map_functions.lua
  tools/map_intro.lua
  tools/map_pregen.lua
  tools/rainbow_colors.lua
  tools/shapes.lua
Labels: live-testing, live-testing-captain, code-cleaning, ready-for-merge

#391 Fix server crash on `debug_getinfo` with `nil` handler
  utils/event_core.lua
Labels: bugfix, live-testing, live-testing-captain, ready-for-merge

#379 Add instant map reset command with optional seed argument
  commands/misc.lua
  maps/biter_battles_v2/game_over.lua
  maps/biter_battles_v2/init.lua
  maps/biter_battles_v2/terrain.lua
Labels: enhancement, live-testing, live-testing-captain, ready-for-merge

#392 New feature : Add /save-quickbar and /load-quickbar commands
  utils/datastore/quickbar_data.lua
  utils/server.lua
Labels: enhancement, live-testing, live-testing-captain, ready-for-merge

#407 Bugfix : total playtime is now logged
  comfy_panel/player_list.lua
  maps/biter_battles_v2/init.lua
  utils/datastore/session_data.lua
  utils/server.lua
Labels: bugfix, live-testing, live-testing-captain, ready-for-merge

#402 Bugfix : ignore works now even if different forces or /sth , /nth or /s used
  commands/chat_commands.lua
  maps/biter_battles_v2/functions.lua
  maps/biter_battles_v2/init.lua
  maps/biter_battles_v2/main.lua
Labels: bugfix, live-testing, live-testing-captain, ready-for-merge

#412 fix boss units not traveling with the pack
  maps/biter_battles_v2/ai.lua
  maps/biter_battles_v2/ai_strikes.lua
Labels: bugfix, live-testing, live-testing-captain, ready-for-merge

#417 Decreased red /green and increased mil/blue science values
  maps/biter_battles_v2/tables.lua
Labels: enhancement, live-testing, live-testing-captain, ready-for-merge

#408 Add a spectator-force log message about which team completed a research
  maps/biter_battles_v2/main.lua
Labels: enhancement, live-testing, live-testing-captain

#405 Add /spectator-chat command
  commands/chat_commands.lua
Labels: enhancement, live-testing, live-testing-captain
