Repository Factorio-Biter-Battles/Factorio-Biter-Battles, pull requests merged in 2023-12, with the labels that each got.

#421 Add comment documenting advantage of sending science in large batches
  maps/biter_battles_v2/feeding.lua
Labels: documentation, live-testing, live-testing-captain

#413 instant map reset can be done during map reroll + default yes map reroll + added possibility cancel map reroll
  commands/misc.lua
  maps/biter_battles_v2/game_over.lua
  maps/biter_battles_v2/init.lua
Labels: bugfix, live-testing, live-testing-captain

#401 perf : Optimize river generation
  maps/biter_battles_v2/precomputed/biter_texture.lua
  maps/biter_battles_v2/precomputed/chunk_container.lua
  maps/biter_battles_v2/precomputed/river.lua
  maps/biter_battles_v2/terrain.lua
Labels: live-testing, live-testing-captain, perf

#422 Reset game speed to 1 after silo death
  maps/biter_battles_v2/game_over.lua
Labels: bugfix, enhancement, live-testing, live-testing-captain

#426 fix poll button opens random player camera
  comfy_panel/player_list.lua
Labels: bugfix, live-testing, live-testing-captain
