Repository Factorio-Biter-Battles/Factorio-Biter-Battles, pull requests merged in 2024-03, with the labels that each got.

#361 Increase the size and edit ratio of mixed patches
  maps/biter_battles_v2/terrain.lua
Labels: enhancement, live-testing, live-testing-captain

#433 Rework of biter terrain texture to be factorio 2.0 compatible
  maps/biter_battles_v2/precomputed/biter_texture.lua
Labels: enhancement, live-testing, live-testing-captain

#435 Fix playtime rank
  comfy_panel/player_list.lua
Labels: bugfix, live-testing, live-testing-captain

#419 Refactor/standardize most code that prints out team names
  maps/biter_battles_v2/ai.lua
  maps/biter_battles_v2/feeding.lua
  maps/biter_battles_v2/functions.lua
  maps/biter_battles_v2/game_over.lua
  maps/biter_battles_v2/gui.lua
  maps/biter_battles_v2/main.lua
  maps/biter_battles_v2/sciencelogs_tab.lua
  maps/biter_battles_v2/team_manager.lua
Labels: live-testing, live-testing-captain, code-cleaning

#436 fix boss_unit death tracking
  functions/boss_unit.lua
Labels: bugfix

#437 Refactor get_formatted_playtime
  comfy_panel/player_list.lua
Labels: code-cleaning
